// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourcesInternal.proto

package android.aapt.pb.internal;

public final class ResourcesInternal {
  private ResourcesInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CompiledFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aapt.pb.internal.CompiledFile)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    java.lang.String getResourceName();
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getResourceNameBytes();

    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    boolean hasConfig();
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    com.android.aapt.ConfigurationOuterClass.Configuration getConfig();

    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    com.android.aapt.Resources.FileReference.Type getType();

    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    java.lang.String getSourcePath();
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    com.google.protobuf.ByteString
        getSourcePathBytes();

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> 
        getExportedSymbolList();
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index);
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    int getExportedSymbolCount();
  }
  /**
   * <pre>
   * The top level message representing an external resource file (layout XML, PNG, etc).
   * This is used to represent a compiled file before it is linked. Only useful to aapt2.
   * </pre>
   *
   * Protobuf type {@code aapt.pb.internal.CompiledFile}
   */
  public  static final class CompiledFile extends
      com.google.protobuf.GeneratedMessageLite<
          CompiledFile, CompiledFile.Builder> implements
      // @@protoc_insertion_point(message_implements:aapt.pb.internal.CompiledFile)
      CompiledFileOrBuilder {
    private CompiledFile() {
      resourceName_ = "";
      sourcePath_ = "";
      exportedSymbol_ = emptyProtobufList();
    }
    public interface SymbolOrBuilder extends
        // @@protoc_insertion_point(interface_extends:aapt.pb.internal.CompiledFile.Symbol)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      java.lang.String getResourceName();
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      com.google.protobuf.ByteString
          getResourceNameBytes();

      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      boolean hasSource();
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      com.android.aapt.Resources.SourcePosition getSource();
    }
    /**
     * Protobuf type {@code aapt.pb.internal.CompiledFile.Symbol}
     */
    public  static final class Symbol extends
        com.google.protobuf.GeneratedMessageLite<
            Symbol, Symbol.Builder> implements
        // @@protoc_insertion_point(message_implements:aapt.pb.internal.CompiledFile.Symbol)
        SymbolOrBuilder {
      private Symbol() {
        resourceName_ = "";
      }
      public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
      private java.lang.String resourceName_;
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getResourceName() {
        return resourceName_;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void setResourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceName_ = value;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void clearResourceName() {
        
        resourceName_ = getDefaultInstance().getResourceName();
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceName_ = value.toStringUtf8();
      }

      public static final int SOURCE_FIELD_NUMBER = 2;
      private com.android.aapt.Resources.SourcePosition source_;
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      @java.lang.Override
      public boolean hasSource() {
        return source_ != null;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      @java.lang.Override
      public com.android.aapt.Resources.SourcePosition getSource() {
        return source_ == null ? com.android.aapt.Resources.SourcePosition.getDefaultInstance() : source_;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void setSource(com.android.aapt.Resources.SourcePosition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        
        }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void setSource(
          com.android.aapt.Resources.SourcePosition.Builder builderForValue) {
        source_ = builderForValue.build();
        
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      @java.lang.SuppressWarnings({"ReferenceEquality"})
      private void mergeSource(com.android.aapt.Resources.SourcePosition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (source_ != null &&
            source_ != com.android.aapt.Resources.SourcePosition.getDefaultInstance()) {
          source_ =
            com.android.aapt.Resources.SourcePosition.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void clearSource() {  source_ = null;
        
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!resourceName_.isEmpty()) {
          output.writeString(1, getResourceName());
        }
        if (source_ != null) {
          output.writeMessage(2, getSource());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!resourceName_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getResourceName());
        }
        if (source_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getSource());
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code aapt.pb.internal.CompiledFile.Symbol}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol, Builder> implements
          // @@protoc_insertion_point(builder_implements:aapt.pb.internal.CompiledFile.Symbol)
          android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder {
        // Construct using android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        @java.lang.Override
        public java.lang.String getResourceName() {
          return instance.getResourceName();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getResourceNameBytes() {
          return instance.getResourceNameBytes();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder setResourceName(
            java.lang.String value) {
          copyOnWrite();
          instance.setResourceName(value);
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder clearResourceName() {
          copyOnWrite();
          instance.clearResourceName();
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder setResourceNameBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setResourceNameBytes(value);
          return this;
        }

        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        @java.lang.Override
        public boolean hasSource() {
          return instance.hasSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        @java.lang.Override
        public com.android.aapt.Resources.SourcePosition getSource() {
          return instance.getSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder setSource(com.android.aapt.Resources.SourcePosition value) {
          copyOnWrite();
          instance.setSource(value);
          return this;
          }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder setSource(
            com.android.aapt.Resources.SourcePosition.Builder builderForValue) {
          copyOnWrite();
          instance.setSource(builderForValue);
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder mergeSource(com.android.aapt.Resources.SourcePosition value) {
          copyOnWrite();
          instance.mergeSource(value);
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder clearSource() {  copyOnWrite();
          instance.clearSource();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:aapt.pb.internal.CompiledFile.Symbol)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol other = (android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol) arg1;
            resourceName_ = visitor.visitString(!resourceName_.isEmpty(), resourceName_,
                !other.resourceName_.isEmpty(), other.resourceName_);
            source_ = visitor.visitMessage(source_, other.source_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            if (extensionRegistry == null) {
              throw new java.lang.NullPointerException();
            }
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  case 10: {
                    java.lang.String s = input.readStringRequireUtf8();

                    resourceName_ = s;
                    break;
                  }
                  case 18: {
                    com.android.aapt.Resources.SourcePosition.Builder subBuilder = null;
                    if (source_ != null) {
                      subBuilder = source_.toBuilder();
                    }
                    source_ = input.readMessage(com.android.aapt.Resources.SourcePosition.parser(), extensionRegistry);
                    if (subBuilder != null) {
                      subBuilder.mergeFrom(source_);
                      source_ = subBuilder.buildPartial();
                    }

                    break;
                  }
                  default: {
                    if (!parseUnknownField(tag, input)) {
                      done = true;
                    }
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> parser = PARSER;
            if (parser == null) {
              synchronized (android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.class) {
                parser = PARSER;
                if (parser == null) {
                  parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFile.Symbol)
      private static final android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol DEFAULT_INSTANCE;
      static {
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = new Symbol();
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Symbol> PARSER;

      public static com.google.protobuf.Parser<Symbol> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
    private java.lang.String resourceName_;
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getResourceName() {
      return resourceName_;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void setResourceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceName_ = value;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void clearResourceName() {
      
      resourceName_ = getDefaultInstance().getResourceName();
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceName_ = value.toStringUtf8();
    }

    public static final int CONFIG_FIELD_NUMBER = 2;
    private com.android.aapt.ConfigurationOuterClass.Configuration config_;
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    @java.lang.Override
    public boolean hasConfig() {
      return config_ != null;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    @java.lang.Override
    public com.android.aapt.ConfigurationOuterClass.Configuration getConfig() {
      return config_ == null ? com.android.aapt.ConfigurationOuterClass.Configuration.getDefaultInstance() : config_;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    private void setConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
      if (value == null) {
        throw new NullPointerException();
      }
      config_ = value;
      
      }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    private void setConfig(
        com.android.aapt.ConfigurationOuterClass.Configuration.Builder builderForValue) {
      config_ = builderForValue.build();
      
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (config_ != null &&
          config_ != com.android.aapt.ConfigurationOuterClass.Configuration.getDefaultInstance()) {
        config_ =
          com.android.aapt.ConfigurationOuterClass.Configuration.newBuilder(config_).mergeFrom(value).buildPartial();
      } else {
        config_ = value;
      }
      
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.Configuration config = 2;</code>
     */
    private void clearConfig() {  config_ = null;
      
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    @java.lang.Override
    public com.android.aapt.Resources.FileReference.Type getType() {
      com.android.aapt.Resources.FileReference.Type result = com.android.aapt.Resources.FileReference.Type.forNumber(type_);
      return result == null ? com.android.aapt.Resources.FileReference.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    private void setType(com.android.aapt.Resources.FileReference.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.aapt.pb.FileReference.Type type = 3;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int SOURCE_PATH_FIELD_NUMBER = 4;
    private java.lang.String sourcePath_;
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getSourcePath() {
      return sourcePath_;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourcePathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sourcePath_);
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    private void setSourcePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourcePath_ = value;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    private void clearSourcePath() {
      
      sourcePath_ = getDefaultInstance().getSourcePath();
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    private void setSourcePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourcePath_ = value.toStringUtf8();
    }

    public static final int EXPORTED_SYMBOL_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> exportedSymbol_;
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> getExportedSymbolList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    public java.util.List<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder> 
        getExportedSymbolOrBuilderList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public int getExportedSymbolCount() {
      return exportedSymbol_.size();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index) {
      return exportedSymbol_.get(index);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    public android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder getExportedSymbolOrBuilder(
        int index) {
      return exportedSymbol_.get(index);
    }
    private void ensureExportedSymbolIsMutable() {
      if (!exportedSymbol_.isModifiable()) {
        exportedSymbol_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(exportedSymbol_);
       }
    }

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void setExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.set(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void setExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(
        android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addAllExportedSymbol(
        java.lang.Iterable<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> values) {
      ensureExportedSymbolIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, exportedSymbol_);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void clearExportedSymbol() {
      exportedSymbol_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void removeExportedSymbol(int index) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.remove(index);
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!resourceName_.isEmpty()) {
        output.writeString(1, getResourceName());
      }
      if (config_ != null) {
        output.writeMessage(2, getConfig());
      }
      if (type_ != com.android.aapt.Resources.FileReference.Type.UNKNOWN.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!sourcePath_.isEmpty()) {
        output.writeString(4, getSourcePath());
      }
      for (int i = 0; i < exportedSymbol_.size(); i++) {
        output.writeMessage(5, exportedSymbol_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!resourceName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getResourceName());
      }
      if (config_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfig());
      }
      if (type_ != com.android.aapt.Resources.FileReference.Type.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!sourcePath_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSourcePath());
      }
      for (int i = 0; i < exportedSymbol_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, exportedSymbol_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(android.aapt.pb.internal.ResourcesInternal.CompiledFile prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The top level message representing an external resource file (layout XML, PNG, etc).
     * This is used to represent a compiled file before it is linked. Only useful to aapt2.
     * </pre>
     *
     * Protobuf type {@code aapt.pb.internal.CompiledFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          android.aapt.pb.internal.ResourcesInternal.CompiledFile, Builder> implements
        // @@protoc_insertion_point(builder_implements:aapt.pb.internal.CompiledFile)
        android.aapt.pb.internal.ResourcesInternal.CompiledFileOrBuilder {
      // Construct using android.aapt.pb.internal.ResourcesInternal.CompiledFile.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getResourceName() {
        return instance.getResourceName();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return instance.getResourceNameBytes();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder setResourceName(
          java.lang.String value) {
        copyOnWrite();
        instance.setResourceName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder clearResourceName() {
        copyOnWrite();
        instance.clearResourceName();
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResourceNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      @java.lang.Override
      public boolean hasConfig() {
        return instance.hasConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      @java.lang.Override
      public com.android.aapt.ConfigurationOuterClass.Configuration getConfig() {
        return instance.getConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      public Builder setConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
        copyOnWrite();
        instance.setConfig(value);
        return this;
        }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      public Builder setConfig(
          com.android.aapt.ConfigurationOuterClass.Configuration.Builder builderForValue) {
        copyOnWrite();
        instance.setConfig(builderForValue);
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      public Builder mergeConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
        copyOnWrite();
        instance.mergeConfig(value);
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.Configuration config = 2;</code>
       */
      public Builder clearConfig() {  copyOnWrite();
        instance.clearConfig();
        return this;
      }

      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.aapt.pb.FileReference.Type type = 3;</code>
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.aapt.pb.FileReference.Type type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.aapt.pb.FileReference.Type type = 3;</code>
       */
      @java.lang.Override
      public com.android.aapt.Resources.FileReference.Type getType() {
        return instance.getType();
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.aapt.pb.FileReference.Type type = 3;</code>
       */
      public Builder setType(com.android.aapt.Resources.FileReference.Type value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.aapt.pb.FileReference.Type type = 3;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       */
      @java.lang.Override
      public java.lang.String getSourcePath() {
        return instance.getSourcePath();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSourcePathBytes() {
        return instance.getSourcePathBytes();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       */
      public Builder setSourcePath(
          java.lang.String value) {
        copyOnWrite();
        instance.setSourcePath(value);
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       */
      public Builder clearSourcePath() {
        copyOnWrite();
        instance.clearSourcePath();
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       */
      public Builder setSourcePathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourcePathBytes(value);
        return this;
      }

      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> getExportedSymbolList() {
        return java.util.Collections.unmodifiableList(
            instance.getExportedSymbolList());
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public int getExportedSymbolCount() {
        return instance.getExportedSymbolCount();
      }/**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index) {
        return instance.getExportedSymbol(index);
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder setExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.setExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder setExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.setExportedSymbol(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addAllExportedSymbol(
          java.lang.Iterable<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> values) {
        copyOnWrite();
        instance.addAllExportedSymbol(values);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder clearExportedSymbol() {
        copyOnWrite();
        instance.clearExportedSymbol();
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder removeExportedSymbol(int index) {
        copyOnWrite();
        instance.removeExportedSymbol(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aapt.pb.internal.CompiledFile)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new android.aapt.pb.internal.ResourcesInternal.CompiledFile();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          exportedSymbol_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          android.aapt.pb.internal.ResourcesInternal.CompiledFile other = (android.aapt.pb.internal.ResourcesInternal.CompiledFile) arg1;
          resourceName_ = visitor.visitString(!resourceName_.isEmpty(), resourceName_,
              !other.resourceName_.isEmpty(), other.resourceName_);
          config_ = visitor.visitMessage(config_, other.config_);
          type_ = visitor.visitInt(type_ != 0, type_,    other.type_ != 0, other.type_);
          sourcePath_ = visitor.visitString(!sourcePath_.isEmpty(), sourcePath_,
              !other.sourcePath_.isEmpty(), other.sourcePath_);
          exportedSymbol_= visitor.visitList(exportedSymbol_, other.exportedSymbol_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  resourceName_ = s;
                  break;
                }
                case 18: {
                  com.android.aapt.ConfigurationOuterClass.Configuration.Builder subBuilder = null;
                  if (config_ != null) {
                    subBuilder = config_.toBuilder();
                  }
                  config_ = input.readMessage(com.android.aapt.ConfigurationOuterClass.Configuration.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(config_);
                    config_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  type_ = rawValue;
                  break;
                }
                case 34: {
                  java.lang.String s = input.readStringRequireUtf8();

                  sourcePath_ = s;
                  break;
                }
                case 42: {
                  if (!exportedSymbol_.isModifiable()) {
                    exportedSymbol_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(exportedSymbol_);
                  }
                  exportedSymbol_.add(
                      input.readMessage(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.parser(), extensionRegistry));
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<android.aapt.pb.internal.ResourcesInternal.CompiledFile> parser = PARSER;
          if (parser == null) {
            synchronized (android.aapt.pb.internal.ResourcesInternal.CompiledFile.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFile)
    private static final android.aapt.pb.internal.ResourcesInternal.CompiledFile DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new CompiledFile();
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CompiledFile> PARSER;

    public static com.google.protobuf.Parser<CompiledFile> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
