// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigurationLegacy.proto

package com.didiglobal.booster.aapt2.legacy;

public final class ConfigurationLegacy {
  private ConfigurationLegacy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ConfigDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aapt.pb.ConfigDescription)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string product = 2;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();
  }
  /**
   * <pre>
   * A configuration description that wraps the binary form of the C++ class
   * aapt::ConfigDescription, with an added product definition.
   * TODO(adamlesinski): Flesh this out to be represented in proto.
   * </pre>
   *
   * Protobuf type {@code aapt.pb.ConfigDescription}
   */
  public  static final class ConfigDescription extends
      com.google.protobuf.GeneratedMessageLite<
          ConfigDescription, ConfigDescription.Builder> implements
      // @@protoc_insertion_point(message_implements:aapt.pb.ConfigDescription)
      ConfigDescriptionOrBuilder {
    private ConfigDescription() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      product_ = "";
    }
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private java.lang.String product_;
    /**
     * <code>string product = 2;</code>
     */
    public java.lang.String getProduct() {
      return product_;
    }
    /**
     * <code>string product = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(product_);
    }
    /**
     * <code>string product = 2;</code>
     */
    private void setProduct(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      product_ = value;
    }
    /**
     * <code>string product = 2;</code>
     */
    private void clearProduct() {
      
      product_ = getDefaultInstance().getProduct();
    }
    /**
     * <code>string product = 2;</code>
     */
    private void setProductBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      product_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!product_.isEmpty()) {
        output.writeString(2, getProduct());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!product_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getProduct());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * A configuration description that wraps the binary form of the C++ class
     * aapt::ConfigDescription, with an added product definition.
     * TODO(adamlesinski): Flesh this out to be represented in proto.
     * </pre>
     *
     * Protobuf type {@code aapt.pb.ConfigDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription, Builder> implements
        // @@protoc_insertion_point(builder_implements:aapt.pb.ConfigDescription)
        com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescriptionOrBuilder {
      // Construct using com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>string product = 2;</code>
       */
      public java.lang.String getProduct() {
        return instance.getProduct();
      }
      /**
       * <code>string product = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        return instance.getProductBytes();
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        copyOnWrite();
        instance.setProduct(value);
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder clearProduct() {
        copyOnWrite();
        instance.clearProduct();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProductBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aapt.pb.ConfigDescription)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription other = (com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription) arg1;
          data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
              other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
          product_ = visitor.visitString(!product_.isEmpty(), product_,
              !other.product_.isEmpty(), other.product_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {

                  data_ = input.readBytes();
                  break;
                }
                case 18: {
                  java.lang.String s = input.readStringRequireUtf8();

                  product_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:aapt.pb.ConfigDescription)
    private static final com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConfigDescription();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.didiglobal.booster.aapt2.legacy.ConfigurationLegacy.ConfigDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ConfigDescription> PARSER;

    public static com.google.protobuf.Parser<ConfigDescription> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
