// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourcesInternalLegacy.proto

package com.didiglobal.booster.aapt2.legacy;

public final class ResourcesInternalLegacy {
  private ResourcesInternalLegacy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ConfigDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aapt.pb.internal.ConfigDescription)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string product = 2;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();
  }
  /**
   * <pre>
   * A configuration description that wraps the binary form of the C++ class
   * aapt::ConfigDescription, with an added product definition.
   * TODO(adamlesinski): Flesh this out to be represented in proto.
   * </pre>
   *
   * Protobuf type {@code aapt.pb.internal.ConfigDescription}
   */
  public  static final class ConfigDescription extends
      com.google.protobuf.GeneratedMessageLite<
          ConfigDescription, ConfigDescription.Builder> implements
      // @@protoc_insertion_point(message_implements:aapt.pb.internal.ConfigDescription)
      ConfigDescriptionOrBuilder {
    private ConfigDescription() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      product_ = "";
    }
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private java.lang.String product_;
    /**
     * <code>string product = 2;</code>
     */
    public java.lang.String getProduct() {
      return product_;
    }
    /**
     * <code>string product = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(product_);
    }
    /**
     * <code>string product = 2;</code>
     */
    private void setProduct(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      product_ = value;
    }
    /**
     * <code>string product = 2;</code>
     */
    private void clearProduct() {
      
      product_ = getDefaultInstance().getProduct();
    }
    /**
     * <code>string product = 2;</code>
     */
    private void setProductBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      product_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!product_.isEmpty()) {
        output.writeString(2, getProduct());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!product_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getProduct());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * A configuration description that wraps the binary form of the C++ class
     * aapt::ConfigDescription, with an added product definition.
     * TODO(adamlesinski): Flesh this out to be represented in proto.
     * </pre>
     *
     * Protobuf type {@code aapt.pb.internal.ConfigDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription, Builder> implements
        // @@protoc_insertion_point(builder_implements:aapt.pb.internal.ConfigDescription)
        com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescriptionOrBuilder {
      // Construct using com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>string product = 2;</code>
       */
      public java.lang.String getProduct() {
        return instance.getProduct();
      }
      /**
       * <code>string product = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        return instance.getProductBytes();
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        copyOnWrite();
        instance.setProduct(value);
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder clearProduct() {
        copyOnWrite();
        instance.clearProduct();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProductBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aapt.pb.internal.ConfigDescription)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription other = (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription) arg1;
          data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
              other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
          product_ = visitor.visitString(!product_.isEmpty(), product_,
              !other.product_.isEmpty(), other.product_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {

                  data_ = input.readBytes();
                  break;
                }
                case 18: {
                  java.lang.String s = input.readStringRequireUtf8();

                  product_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:aapt.pb.internal.ConfigDescription)
    private static final com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConfigDescription();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ConfigDescription> PARSER;

    public static com.google.protobuf.Parser<ConfigDescription> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CompiledFileLegacyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aapt.pb.internal.CompiledFileLegacy)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    java.lang.String getResourceName();
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getResourceNameBytes();

    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    boolean hasConfig();
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription getConfig();

    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    java.lang.String getSourcePath();
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourcePathBytes();

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    java.util.List<com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> 
        getExportedSymbolList();
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol getExportedSymbol(int index);
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    int getExportedSymbolCount();

    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    boolean hasXmlRoot();
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    com.didiglobal.booster.aapt2.Resources.XmlNode getXmlRoot();
  }
  /**
   * <pre>
   * The top level message representing an external resource file (layout XML, PNG, etc).
   * This is used to represent a compiled file before it is linked. Only useful to aapt2.
   * </pre>
   *
   * Protobuf type {@code aapt.pb.internal.CompiledFileLegacy}
   */
  public  static final class CompiledFileLegacy extends
      com.google.protobuf.GeneratedMessageLite<
          CompiledFileLegacy, CompiledFileLegacy.Builder> implements
      // @@protoc_insertion_point(message_implements:aapt.pb.internal.CompiledFileLegacy)
      CompiledFileLegacyOrBuilder {
    private CompiledFileLegacy() {
      resourceName_ = "";
      sourcePath_ = "";
      exportedSymbol_ = emptyProtobufList();
    }
    public interface SymbolOrBuilder extends
        // @@protoc_insertion_point(interface_extends:aapt.pb.internal.CompiledFileLegacy.Symbol)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      java.lang.String getResourceName();
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      com.google.protobuf.ByteString
          getResourceNameBytes();

      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      boolean hasSource();
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      com.didiglobal.booster.aapt2.Resources.SourcePosition getSource();
    }
    /**
     * Protobuf type {@code aapt.pb.internal.CompiledFileLegacy.Symbol}
     */
    public  static final class Symbol extends
        com.google.protobuf.GeneratedMessageLite<
            Symbol, Symbol.Builder> implements
        // @@protoc_insertion_point(message_implements:aapt.pb.internal.CompiledFileLegacy.Symbol)
        SymbolOrBuilder {
      private Symbol() {
        resourceName_ = "";
      }
      public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
      private java.lang.String resourceName_;
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public java.lang.String getResourceName() {
        return resourceName_;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void setResourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceName_ = value;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void clearResourceName() {
        
        resourceName_ = getDefaultInstance().getResourceName();
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceName_ = value.toStringUtf8();
      }

      public static final int SOURCE_FIELD_NUMBER = 2;
      private com.didiglobal.booster.aapt2.Resources.SourcePosition source_;
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      public boolean hasSource() {
        return source_ != null;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      public com.didiglobal.booster.aapt2.Resources.SourcePosition getSource() {
        return source_ == null ? com.didiglobal.booster.aapt2.Resources.SourcePosition.getDefaultInstance() : source_;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void setSource(com.didiglobal.booster.aapt2.Resources.SourcePosition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        
        }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void setSource(
          com.didiglobal.booster.aapt2.Resources.SourcePosition.Builder builderForValue) {
        source_ = builderForValue.build();
        
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void mergeSource(com.didiglobal.booster.aapt2.Resources.SourcePosition value) {
        if (source_ != null &&
            source_ != com.didiglobal.booster.aapt2.Resources.SourcePosition.getDefaultInstance()) {
          source_ =
            com.didiglobal.booster.aapt2.Resources.SourcePosition.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.aapt.pb.SourcePosition source = 2;</code>
       */
      private void clearSource() {  source_ = null;
        
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!resourceName_.isEmpty()) {
          output.writeString(1, getResourceName());
        }
        if (source_ != null) {
          output.writeMessage(2, getSource());
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!resourceName_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getResourceName());
        }
        if (source_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getSource());
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code aapt.pb.internal.CompiledFileLegacy.Symbol}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol, Builder> implements
          // @@protoc_insertion_point(builder_implements:aapt.pb.internal.CompiledFileLegacy.Symbol)
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.SymbolOrBuilder {
        // Construct using com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public java.lang.String getResourceName() {
          return instance.getResourceName();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getResourceNameBytes() {
          return instance.getResourceNameBytes();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder setResourceName(
            java.lang.String value) {
          copyOnWrite();
          instance.setResourceName(value);
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder clearResourceName() {
          copyOnWrite();
          instance.clearResourceName();
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         */
        public Builder setResourceNameBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setResourceNameBytes(value);
          return this;
        }

        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public boolean hasSource() {
          return instance.hasSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public com.didiglobal.booster.aapt2.Resources.SourcePosition getSource() {
          return instance.getSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder setSource(com.didiglobal.booster.aapt2.Resources.SourcePosition value) {
          copyOnWrite();
          instance.setSource(value);
          return this;
          }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder setSource(
            com.didiglobal.booster.aapt2.Resources.SourcePosition.Builder builderForValue) {
          copyOnWrite();
          instance.setSource(builderForValue);
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder mergeSource(com.didiglobal.booster.aapt2.Resources.SourcePosition value) {
          copyOnWrite();
          instance.mergeSource(value);
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.aapt.pb.SourcePosition source = 2;</code>
         */
        public Builder clearSource() {  copyOnWrite();
          instance.clearSource();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:aapt.pb.internal.CompiledFileLegacy.Symbol)
      }
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol other = (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol) arg1;
            resourceName_ = visitor.visitString(!resourceName_.isEmpty(), resourceName_,
                !other.resourceName_.isEmpty(), other.resourceName_);
            source_ = visitor.visitMessage(source_, other.source_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!parseUnknownField(tag, input)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    java.lang.String s = input.readStringRequireUtf8();

                    resourceName_ = s;
                    break;
                  }
                  case 18: {
                    com.didiglobal.booster.aapt2.Resources.SourcePosition.Builder subBuilder = null;
                    if (source_ != null) {
                      subBuilder = source_.toBuilder();
                    }
                    source_ = input.readMessage(com.didiglobal.booster.aapt2.Resources.SourcePosition.parser(), extensionRegistry);
                    if (subBuilder != null) {
                      subBuilder.mergeFrom(source_);
                      source_ = subBuilder.buildPartial();
                    }

                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFileLegacy.Symbol)
      private static final com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Symbol();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Symbol> PARSER;

      public static com.google.protobuf.Parser<Symbol> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
    private java.lang.String resourceName_;
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public java.lang.String getResourceName() {
      return resourceName_;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void setResourceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceName_ = value;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void clearResourceName() {
      
      resourceName_ = getDefaultInstance().getResourceName();
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceName_ = value.toStringUtf8();
    }

    public static final int CONFIG_FIELD_NUMBER = 2;
    private com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription config_;
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    public boolean hasConfig() {
      return config_ != null;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    public com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription getConfig() {
      return config_ == null ? com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.getDefaultInstance() : config_;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    private void setConfig(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription value) {
      if (value == null) {
        throw new NullPointerException();
      }
      config_ = value;
      
      }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    private void setConfig(
        com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.Builder builderForValue) {
      config_ = builderForValue.build();
      
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    private void mergeConfig(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription value) {
      if (config_ != null &&
          config_ != com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.getDefaultInstance()) {
        config_ =
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.newBuilder(config_).mergeFrom(value).buildPartial();
      } else {
        config_ = value;
      }
      
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
     */
    private void clearConfig() {  config_ = null;
      
    }

    public static final int SOURCE_PATH_FIELD_NUMBER = 3;
    private java.lang.String sourcePath_;
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    public java.lang.String getSourcePath() {
      return sourcePath_;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourcePathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sourcePath_);
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    private void setSourcePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourcePath_ = value;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    private void clearSourcePath() {
      
      sourcePath_ = getDefaultInstance().getSourcePath();
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 3;</code>
     */
    private void setSourcePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourcePath_ = value.toStringUtf8();
    }

    public static final int EXPORTED_SYMBOL_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> exportedSymbol_;
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    public java.util.List<com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> getExportedSymbolList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    public java.util.List<? extends com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.SymbolOrBuilder> 
        getExportedSymbolOrBuilderList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    public int getExportedSymbolCount() {
      return exportedSymbol_.size();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    public com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol getExportedSymbol(int index) {
      return exportedSymbol_.get(index);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    public com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.SymbolOrBuilder getExportedSymbolOrBuilder(
        int index) {
      return exportedSymbol_.get(index);
    }
    private void ensureExportedSymbolIsMutable() {
      if (!exportedSymbol_.isModifiable()) {
        exportedSymbol_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(exportedSymbol_);
       }
    }

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void setExportedSymbol(
        int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.set(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void setExportedSymbol(
        int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void addExportedSymbol(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void addExportedSymbol(
        int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void addExportedSymbol(
        com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void addExportedSymbol(
        int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void addAllExportedSymbol(
        java.lang.Iterable<? extends com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> values) {
      ensureExportedSymbolIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, exportedSymbol_);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void clearExportedSymbol() {
      exportedSymbol_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
     */
    private void removeExportedSymbol(int index) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.remove(index);
    }

    public static final int XML_ROOT_FIELD_NUMBER = 5;
    private com.didiglobal.booster.aapt2.Resources.XmlNode xmlRoot_;
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    public boolean hasXmlRoot() {
      return xmlRoot_ != null;
    }
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    public com.didiglobal.booster.aapt2.Resources.XmlNode getXmlRoot() {
      return xmlRoot_ == null ? com.didiglobal.booster.aapt2.Resources.XmlNode.getDefaultInstance() : xmlRoot_;
    }
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    private void setXmlRoot(com.didiglobal.booster.aapt2.Resources.XmlNode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      xmlRoot_ = value;
      
      }
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    private void setXmlRoot(
        com.didiglobal.booster.aapt2.Resources.XmlNode.Builder builderForValue) {
      xmlRoot_ = builderForValue.build();
      
    }
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    private void mergeXmlRoot(com.didiglobal.booster.aapt2.Resources.XmlNode value) {
      if (xmlRoot_ != null &&
          xmlRoot_ != com.didiglobal.booster.aapt2.Resources.XmlNode.getDefaultInstance()) {
        xmlRoot_ =
          com.didiglobal.booster.aapt2.Resources.XmlNode.newBuilder(xmlRoot_).mergeFrom(value).buildPartial();
      } else {
        xmlRoot_ = value;
      }
      
    }
    /**
     * <pre>
     * If this is a compiled XML file, this is the root node.
     * </pre>
     *
     * <code>.aapt.pb.XmlNode xml_root = 5;</code>
     */
    private void clearXmlRoot() {  xmlRoot_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!resourceName_.isEmpty()) {
        output.writeString(1, getResourceName());
      }
      if (config_ != null) {
        output.writeMessage(2, getConfig());
      }
      if (!sourcePath_.isEmpty()) {
        output.writeString(3, getSourcePath());
      }
      for (int i = 0; i < exportedSymbol_.size(); i++) {
        output.writeMessage(4, exportedSymbol_.get(i));
      }
      if (xmlRoot_ != null) {
        output.writeMessage(5, getXmlRoot());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!resourceName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getResourceName());
      }
      if (config_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfig());
      }
      if (!sourcePath_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSourcePath());
      }
      for (int i = 0; i < exportedSymbol_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exportedSymbol_.get(i));
      }
      if (xmlRoot_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getXmlRoot());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * The top level message representing an external resource file (layout XML, PNG, etc).
     * This is used to represent a compiled file before it is linked. Only useful to aapt2.
     * </pre>
     *
     * Protobuf type {@code aapt.pb.internal.CompiledFileLegacy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy, Builder> implements
        // @@protoc_insertion_point(builder_implements:aapt.pb.internal.CompiledFileLegacy)
        com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacyOrBuilder {
      // Construct using com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public java.lang.String getResourceName() {
        return instance.getResourceName();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return instance.getResourceNameBytes();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder setResourceName(
          java.lang.String value) {
        copyOnWrite();
        instance.setResourceName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder clearResourceName() {
        copyOnWrite();
        instance.clearResourceName();
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      public Builder setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResourceNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public boolean hasConfig() {
        return instance.hasConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription getConfig() {
        return instance.getConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public Builder setConfig(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription value) {
        copyOnWrite();
        instance.setConfig(value);
        return this;
        }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public Builder setConfig(
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.Builder builderForValue) {
        copyOnWrite();
        instance.setConfig(builderForValue);
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public Builder mergeConfig(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription value) {
        copyOnWrite();
        instance.mergeConfig(value);
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.aapt.pb.internal.ConfigDescription config = 2;</code>
       */
      public Builder clearConfig() {  copyOnWrite();
        instance.clearConfig();
        return this;
      }

      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 3;</code>
       */
      public java.lang.String getSourcePath() {
        return instance.getSourcePath();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourcePathBytes() {
        return instance.getSourcePathBytes();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 3;</code>
       */
      public Builder setSourcePath(
          java.lang.String value) {
        copyOnWrite();
        instance.setSourcePath(value);
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 3;</code>
       */
      public Builder clearSourcePath() {
        copyOnWrite();
        instance.clearSourcePath();
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 3;</code>
       */
      public Builder setSourcePathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourcePathBytes(value);
        return this;
      }

      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public java.util.List<com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> getExportedSymbolList() {
        return java.util.Collections.unmodifiableList(
            instance.getExportedSymbolList());
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public int getExportedSymbolCount() {
        return instance.getExportedSymbolCount();
      }/**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol getExportedSymbol(int index) {
        return instance.getExportedSymbol(index);
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder setExportedSymbol(
          int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
        copyOnWrite();
        instance.setExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder setExportedSymbol(
          int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.setExportedSymbol(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder addExportedSymbol(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder addExportedSymbol(
          int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder addExportedSymbol(
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder addExportedSymbol(
          int index, com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder addAllExportedSymbol(
          java.lang.Iterable<? extends com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol> values) {
        copyOnWrite();
        instance.addAllExportedSymbol(values);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder clearExportedSymbol() {
        copyOnWrite();
        instance.clearExportedSymbol();
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .aapt.pb.internal.CompiledFileLegacy.Symbol exported_symbol = 4;</code>
       */
      public Builder removeExportedSymbol(int index) {
        copyOnWrite();
        instance.removeExportedSymbol(index);
        return this;
      }

      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public boolean hasXmlRoot() {
        return instance.hasXmlRoot();
      }
      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public com.didiglobal.booster.aapt2.Resources.XmlNode getXmlRoot() {
        return instance.getXmlRoot();
      }
      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public Builder setXmlRoot(com.didiglobal.booster.aapt2.Resources.XmlNode value) {
        copyOnWrite();
        instance.setXmlRoot(value);
        return this;
        }
      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public Builder setXmlRoot(
          com.didiglobal.booster.aapt2.Resources.XmlNode.Builder builderForValue) {
        copyOnWrite();
        instance.setXmlRoot(builderForValue);
        return this;
      }
      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public Builder mergeXmlRoot(com.didiglobal.booster.aapt2.Resources.XmlNode value) {
        copyOnWrite();
        instance.mergeXmlRoot(value);
        return this;
      }
      /**
       * <pre>
       * If this is a compiled XML file, this is the root node.
       * </pre>
       *
       * <code>.aapt.pb.XmlNode xml_root = 5;</code>
       */
      public Builder clearXmlRoot() {  copyOnWrite();
        instance.clearXmlRoot();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aapt.pb.internal.CompiledFileLegacy)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          exportedSymbol_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy other = (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy) arg1;
          resourceName_ = visitor.visitString(!resourceName_.isEmpty(), resourceName_,
              !other.resourceName_.isEmpty(), other.resourceName_);
          config_ = visitor.visitMessage(config_, other.config_);
          sourcePath_ = visitor.visitString(!sourcePath_.isEmpty(), sourcePath_,
              !other.sourcePath_.isEmpty(), other.sourcePath_);
          exportedSymbol_= visitor.visitList(exportedSymbol_, other.exportedSymbol_);
          xmlRoot_ = visitor.visitMessage(xmlRoot_, other.xmlRoot_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  resourceName_ = s;
                  break;
                }
                case 18: {
                  com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.Builder subBuilder = null;
                  if (config_ != null) {
                    subBuilder = config_.toBuilder();
                  }
                  config_ = input.readMessage(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.ConfigDescription.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(config_);
                    config_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();

                  sourcePath_ = s;
                  break;
                }
                case 34: {
                  if (!exportedSymbol_.isModifiable()) {
                    exportedSymbol_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(exportedSymbol_);
                  }
                  exportedSymbol_.add(
                      input.readMessage(com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.Symbol.parser(), extensionRegistry));
                  break;
                }
                case 42: {
                  com.didiglobal.booster.aapt2.Resources.XmlNode.Builder subBuilder = null;
                  if (xmlRoot_ != null) {
                    subBuilder = xmlRoot_.toBuilder();
                  }
                  xmlRoot_ = input.readMessage(com.didiglobal.booster.aapt2.Resources.XmlNode.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(xmlRoot_);
                    xmlRoot_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFileLegacy)
    private static final com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CompiledFileLegacy();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.didiglobal.booster.aapt2.legacy.ResourcesInternalLegacy.CompiledFileLegacy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CompiledFileLegacy> PARSER;

    public static com.google.protobuf.Parser<CompiledFileLegacy> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
