package com.didiglobal.booster.aapt2

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class Aapt2ParserTest {

    @Test
    fun `parse xml generated by 3_2_0`() {
        assertLayoutParsing("3.2.0")
    }

    @Test
    fun `parse xml generated by 3_2_1`() {
        assertLayoutParsing("3.2.1")
    }

    @Test
    fun `parse xml generated by 3_3_0`() {
        assertLayoutParsing("3.3.0")
    }

    @Test
    fun `parse xml generated by 3_3_1`() {
        assertLayoutParsing("3.3.1")
    }

    @Test
    fun `parse xml generated by 3_3_2`() {
        assertLayoutParsing("3.3.2")
    }

    @Test
    fun `parse xml generated by 3_4_0`() {
        assertLayoutParsing("3.4.0")
    }

    @Test
    fun `parse xml generated by 3_4_1`() {
        assertLayoutParsing("3.4.1")
    }

    fun assertLayoutParsing(version: String) {
        val xml = File(javaClass.getResource("$version${File.separator}layout_activity_main.xml.flat").file)
        assertTrue(xml.exists())

        val container = BinaryParser(xml).use { parser ->
            parser.parseAapt2Container()
        }
        assertEquals(1, container.header.count)

        val layout = container.entries.single() as Aapt2Container.Xml
        assertEquals("RelativeLayout", layout.root.element.name)
    }

}
