package com.didiglobal.booster.kotlinx

const val ESC = '\u001B'

const val RESET = "$ESC[0m"

const val BOLD = "$ESC[1m"
const val UNDERLINE = "$ESC[4m"
const val BLINK = "$ESC[5m"
const val REVERSED = "$ESC[7m"

const val BLACK = "$ESC[30m"
const val RED = "$ESC[31m"
const val GREEN = "$ESC[32m"
const val YELLOW = "$ESC[33m"
const val BLUE = "$ESC[34m"
const val MAGENTA = "$ESC[35m"
const val CYAN = "$ESC[36m"
const val WHITE = "$ESC[37m"
const val BRIGHT_BLACK = "$ESC[30,1m"
const val BRIGHT_RED = "$ESC[31,1m"
const val BRIGHT_GREEN = "$ESC[32,1m"
const val BRIGHT_YELLOW = "$ESC[33,1m"
const val BRIGHT_BLUE = "$ESC[34,1m"
const val BRIGHT_MAGENTA = "$ESC[35,1m"
const val BRIGHT_CYAN = "$ESC[36,1m"
const val BRIGHT_WHITE = "$ESC[37,1m"

const val BACKGROUND_BLACK = "$ESC[40m"
const val BACKGROUND_RED = "$ESC[41m"
const val BACKGROUND_GREEN = "$ESC[42m"
const val BACKGROUND_YELLOW = "$ESC[43m"
const val BACKGROUND_BLUE = "$ESC[44m"
const val BACKGROUND_MAGENTA = "$ESC[45m"
const val BACKGROUND_CYAN = "$ESC[46m"
const val BACKGROUND_WHITE = "$ESC[47m"
const val BACKGROUND_BRIGHT_BLACK = "$ESC[40,1m"
const val BACKGROUND_BRIGHT_RED = "$ESC[41,1m"
const val BACKGROUND_BRIGHT_GREEN = "$ESC[42,1m"
const val BACKGROUND_BRIGHT_YELLOW = "$ESC[43,1m"
const val BACKGROUND_BRIGHT_BLUE = "$ESC[44,1m"
const val BACKGROUND_BRIGHT_MAGENTA = "$ESC[45,1m"
const val BACKGROUND_BRIGHT_CYAN = "$ESC[46,1m"
const val BACKGROUND_BRIGHT_WHITE = "$ESC[47,1m"
