name: Run unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  repository_dispatch:
    types: [test]

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: build
      run: ./gradlew assemble -S --no-daemon
